-- Seed all 50 US states with FIPS codes
INSERT INTO "states" ("abbreviation", "name", "fips_code", "priority") VALUES
('AL', 'Alabama', '01', 0),
('AK', 'Alaska', '02', 0),
('AZ', 'Arizona', '04', 0),
('AR', 'Arkansas', '05', 0),
('CA', 'California', '06', 0),
('CO', 'Colorado', '08', 0),
('CT', 'Connecticut', '09', 0),
('DE', 'Delaware', '10', 0),
('FL', 'Florida', '12', 0),
('GA', 'Georgia', '13', 0),
('HI', 'Hawaii', '15', 0),
('ID', 'Idaho', '16', 0),
('IL', 'Illinois', '17', 0),
('IN', 'Indiana', '18', 0),
('IA', 'Iowa', '19', 0),
('KS', 'Kansas', '20', 0),
('KY', 'Kentucky', '21', 0),
('LA', 'Louisiana', '22', 0),
('ME', 'Maine', '23', 0),
('MD', 'Maryland', '24', 0),
('MA', 'Massachusetts', '25', 0),
('MI', 'Michigan', '26', 0),
('MN', 'Minnesota', '27', 0),
('MS', 'Mississippi', '28', 0),
('MO', 'Missouri', '29', 0),
('MT', 'Montana', '30', 0),
('NE', 'Nebraska', '31', 0),
('NV', 'Nevada', '32', 0),
('NH', 'New Hampshire', '33', 0),
('NJ', 'New Jersey', '34', 0),
('NM', 'New Mexico', '35', 0),
('NY', 'New York', '36', 0),
('NC', 'North Carolina', '37', 0),
('ND', 'North Dakota', '38', 0),
('OH', 'Ohio', '39', 0),
('OK', 'Oklahoma', '40', 0),
('OR', 'Oregon', '41', 0),
('PA', 'Pennsylvania', '42', 0),
('RI', 'Rhode Island', '44', 0),
('SC', 'South Carolina', '45', 0),
('SD', 'South Dakota', '46', 0),
('TN', 'Tennessee', '47', 0),
('TX', 'Texas', '48', 0),
('UT', 'Utah', '49', 0),
('VT', 'Vermont', '50', 0),
('VA', 'Virginia', '51', 0),
('WA', 'Washington', '53', 0),
('WV', 'West Virginia', '54', 0),
('WI', 'Wisconsin', '55', 0),
('WY', 'Wyoming', '56', 0)
ON CONFLICT ("abbreviation") DO NOTHING;

-- Insert default FOIA template
INSERT INTO "foia_templates" ("name", "subject_line", "body_text", "is_default") VALUES
('Standard FOIA Request', 
 'FOIA Request - Tax Delinquent Property List - {{county_name}} County, {{state_name}}',
 E'Dear {{official_title}} {{official_name}},\n\nI am writing to request access to public records under the {{state_name}} Freedom of Information Act (or applicable public records law).\n\nSpecifically, I am requesting a list of tax delinquent properties in {{county_name}} County, {{state_name}}. I am interested in obtaining the following information for each property:\n\n• Parcel/Property ID number (APN)\n• Property address or legal description\n• Owner name(s)\n• Mailing address of record\n• Amount of taxes owed\n• Tax year(s) delinquent\n\nFormat: If available, I would prefer the data in electronic format (CSV, Excel, or PDF).\n\nPurpose: This information will be used for research purposes related to real estate investment and community development.\n\nPlease let me know:\n1. If this information is available\n2. The format(s) in which it can be provided\n3. Any associated costs for reproduction\n4. The estimated timeframe for fulfillment\n\nIf there are any fees associated with this request, please inform me before processing. I am willing to pay reasonable reproduction costs.\n\nThank you for your assistance with this public records request. I look forward to your response within the timeframe required by law.\n\nSincerely,\n[Your Name]\n[Your Company Name]\n[Your Contact Information]',
 true)
ON CONFLICT ("name") DO NOTHING;
